[versions]

accompanist = "0.36.0"
androidGradlePlugin = "8.13.1"
android-splash = "1.1.0-rc01"
androidx-navigation = "2.9.5"
compose-activity = "1.11.0"
compose-bom = "2025.11.00"
androidx-lifecycle = "2.9.4"
appcenter = "5.0.2"
apollo = "3.8.2"
crashlytics-plugin = "3.0.6"
crashkios = "0.6.0"
killswitch = "1.0.6"
koin = "4.1.1"
koin-android = "4.1.1"
koin-androidx-compose = "4.1.1"
koin-annotations = "2.1.0"
ksp = "2.3.2"
kotlin = "2.2.21"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
kotlinx-datetime = "0.7.1"
ktor = "3.2.2"
kword-plugin = "4.0.0"
ktlint = "13.1.0"
firebase = "34.3.0"
mockk = "1.12.5"
okio = "3.16.0"
owasp = "8.4.2"
skie = "0.10.8"
trikot = "5.5.0-dev2737"
pilot = "0.3.4"
material3Android = "1.3.1"

[libraries]
accompanist-placeholder-material = { module = "com.google.accompanist:accompanist-placeholder-material", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
android-splash = { module = "androidx.core:core-splashscreen", version.ref = "android-splash" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "compose-activity" }
compose-animation = { module = "androidx.compose.animation:animation" }
compose-material = { module = "androidx.compose.material:material" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui = { module = "androidx.compose.ui:ui" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
#android-play-services-measurement-api = { group = "com.google.android.gms", name = "play-services-measurement-api", version.ref = "play-services-measurement-api" }
android-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase" }
android-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
android-firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

appcenter = { module = "com.microsoft.appcenter:appcenter-distribute", version.ref = "appcenter"}
appcenter-play = { module = "com.microsoft.appcenter:appcenter-distribute-play", version.ref = "appcenter"}
apollo-runtime = { group = "com.apollographql.apollo3", name = "apollo-runtime" }
crashkios = { module = "co.touchlab:crashkios", version.ref = "crashkios" }
killswitch = { module = "com.mirego.killswitch-mobile:killswitch", version.ref = "killswitch" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
ksp-koinCompiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-androidx-compose" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation", version.ref = "koin-androidx-compose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-io = { module = "io.ktor:ktor-io", version.ref = "ktor" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
skie = { module = "co.touchlab.skie:configuration-annotations", version.ref = "skie" }

mockk-common = { module = "io.mockk:mockk-common", version.ref = "mockk" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

trikot-analytics = { module = "com.mirego.trikot:analytics", version.ref = "trikot" }
trikot-analytics-firebase = { module = "com.mirego.trikot.analytics:firebase-ktx", version.ref = "trikot" }
trikot-kword = { module = "com.mirego.trikot:kword", version.ref = "trikot" }
trikot-datasources = { module = "com.mirego.trikot:datasources-flow", version.ref = "trikot" }
pilot-viewmodel = { module = "com.mirego.pilot:viewmodel", version.ref = "pilot" }
pilot-navigation = { module = "com.mirego.pilot:navigation", version.ref = "pilot" }
pilot-components = { module = "com.mirego.pilot:components", version.ref = "pilot" }
pilot-components-material3 = { module = "com.mirego.pilot:components-material3", version.ref = "pilot" }
pilot-components-coil = { module = "com.mirego.pilot:components-coil", version.ref = "pilot" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
apollo-graphql = { id = "com.apollographql.apollo3", version.ref = "apollo" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinx-serialization = { id = "kotlinx-serialization" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
crashlyticsPlugin = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-plugin" }
mirego-kwordPlugin = { id = "mirego.kword", version.ref = "kword-plugin" }
owasp-dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "owasp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
skie-plugin = { id = "co.touchlab.skie", version.ref = "skie" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation" }

[bundles]
