disabled_rules:
  - force_cast
  - function_body_length
  - discouraged_optional_collection
  - type_name
  - private_over_fileprivate
  - multiple_closures_with_trailing_closure
  - inclusive_language
  - blanket_disable_command
  - switch_case_alignment

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - xct_specific_matcher
  - yoda_condition

analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

excluded:
  - Pods
  - Data
  - R.generated.swift
  - .bundle

conditional_returns_on_newline:
  if_only: true

# Use the same deployment target as the project
deployment_target:
  iOS_deployment_target: 15.0

file_length:
  ignore_comment_only_lines: true

line_length: 240

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

unused_declaration:
  include_public_and_open: true

file_header:
  forbidden_string: //

identifier_name: # exclude length validation
  min_length: 1
  max_length: 999

cyclomatic_complexity:
  ignores_case_statements: true

discouraged_object_literal:
  color_literal: false
