# Unless otherwise noted, rules are disabled because they reduce the readability of the code
# See https://realm.github.io/SwiftLint/rule-directory.html for more info on each rule

# Rule identifiers to exclude from running
disabled_rules:
  - comment_spacing
  - force_cast
  - function_body_length

# All opt-in rules are listed, with the ones we do not want commented out so we can know which rules we don't want and which rules are new when upgrading Swiftlint
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  #- closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  #- explicit_acl
  #- explicit_enum_raw_value
  - explicit_init
  - explicit_self
  #- explicit_top_level_acl
  #- explicit_type_interface
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  #- file_name
  - file_name_no_space
  #- file_types_order
  - first_where
  - flatmap_over_map_reduce
  #- force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  #- implicitly_unwrapped_optional
  #- indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  #- lower_acl_than_parent
  #- missing_docs
  - modifier_order
  #- multiline_arguments
  #- multiline_arguments_brackets
  #- multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_extension_access_modifier
  #- no_grouping_extension
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  #- required_deinit
  #- required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  #- switch_case_on_newline
  - toggle_bool
  - trailing_closure
  #- type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  #- vertical_parameter_alignment_on_call
  #- vertical_whitespace_between_cases
  #- vertical_whitespace_closing_braces
  #- vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Paths to exclude
excluded:
  - Pods
  - Data
  - R.generated.swift
  - .bundle
  # Add your own exclusion here

conditional_returns_on_newline:
  if_only: true

# Use the same deployment target as the project
deployment_target:
   iOS_deployment_target: 9.0
   tvOS_deployment_target: 9.1
   watchOS_deployment_target: 2.0

file_length:
  ignore_comment_only_lines: true

line_length: 240

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

unused_declaration:
  include_public_and_open: true

file_header:
  forbidden_string: //

identifier_name: # exclude length validation
  min_length: 1
  max_length: 999

cyclomatic_complexity:
  ignores_case_statements: true

discouraged_object_literal:
  color_literal: false

attributes:
  always_on_line_above: ["@objc"]
