target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'Shared', :path => '../shared'

  pod 'SwiftLint'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
